import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#0F172A",
  },
  backgroundContainer: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    overflow: "hidden",
  },
  backgroundGradient: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    height: "100%",
    backgroundColor: "#1E3A8A",
  },
  backgroundBlob1: {
    position: "absolute",
    top: -50,
    right: -80,
    width: 300,
    height: 300,
    borderRadius: 150,
    backgroundColor: "#3B82F6",
    opacity: 0.3,
  },
  backgroundBlob2: {
    position: "absolute",
    bottom: -100,
    left: -100,
    width: 250,
    height: 250,
    borderRadius: 125,
    backgroundColor: "#2563EB",
    opacity: 0.2,
  },
  scrollContainer: {
    flex: 1,
  },
  conteudo: {
    paddingHorizontal: 28,
    paddingTop: 60,
    paddingBottom: 40,
  },
  botaoVoltar: {
    marginBottom: 20,
  },
  botaoVoltarTexto: {
    color: "#60A5FA",
    fontSize: 14,
    fontWeight: "600",
  },
  logoContainer: {
    alignItems: "center",
    marginBottom: 32,
    marginTop: 0,
  },
  logoBg: {
    width: 120,
    height: 120,
    borderRadius: 60,
    backgroundColor: "#FFFFFF",
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.25,
    shadowRadius: 24,
    elevation: 12,
  },
  logoEmoji: {
    fontSize: 64,
  },
  titulo: {
    fontSize: 32,
    fontWeight: "800",
    color: "#FFFFFF",
    textAlign: "center",
    marginBottom: 12,
    letterSpacing: -0.5,
  },
  subtitulo: {
    fontSize: 16,
    color: "#CBD5E1",
    textAlign: "center",
    marginBottom: 12,
    lineHeight: 24,
  },
  textoInfo: {
    fontSize: 14,
    color: "#94A3B8",
    textAlign: "center",
    marginBottom: 28,
    lineHeight: 20,
  },
  spacer: {
    height: 40,
  },
  inputContainer: {
    marginBottom: 20,
  },
  label: {
    fontSize: 14,
    fontWeight: "700",
    color: "#F1F5F9",
    marginBottom: 10,
    letterSpacing: 0.5,
  },
  inputWrapper: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#1E293B",
    borderRadius: 14,
    paddingHorizontal: 16,
    borderWidth: 1,
    borderColor: "#334155",
  },
  input: {
    flex: 1,
    paddingVertical: 14,
    fontSize: 16,
    color: "#F1F5F9",
  },
  esqueceuSenha: {
    alignSelf: "flex-end",
    marginBottom: 28,
    marginTop: 8,
  },
  esqueceuSenhaTexto: {
    color: "#60A5FA",
    fontSize: 14,
    fontWeight: "600",
  },
  botaoLogin: {
    backgroundColor: "#3B82F6",
    paddingVertical: 16,
    borderRadius: 14,
    alignItems: "center",
    marginBottom: 28,
    shadowColor: "#3B82F6",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.35,
    shadowRadius: 16,
    elevation: 8,
  },
  botaoLoginTexto: {
    color: "#FFFFFF",
    fontSize: 18,
    fontWeight: "700",
    letterSpacing: 0.5,
  },
  divider: {
    height: 1,
    backgroundColor: "#334155",
    marginBottom: 24,
  },
  cadastroBgContainer: {
    backgroundColor: "#1E293B",
    paddingHorizontal: 20,
    paddingVertical: 14,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#334155",
  },
  cadastroContainer: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
  },
  cadastroTexto: {
    color: "#94A3B8",
    fontSize: 15,
  },
  cadastroLink: {
    color: "#60A5FA",
    fontSize: 15,
    fontWeight: "700",
  },
});
